import { ApiProperty } from "@nestjs/swagger";

export class AttachmentDto {

    @ApiProperty({ description: 'Attachment ID' })
    id: number;

    @ApiProperty({ description: 'File autogenerated name' })
    fileName: string;

    @ApiProperty({ description: 'File original name' })
    originalName: string;

    @ApiProperty({ description: 'User Dreated Date' })
    created_at: Date;

    @ApiProperty({ description: 'User Updated Date' })
    updated_at: Date;

    @ApiProperty({ description: 'User Deleted Date', nullable: true })
    deleted_at?: Date;
}