import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString } from "class-validator";

export class CreateAttachmentDto {

    @ApiProperty({ description: 'File autogenerated name' })
    @IsNotEmpty()
    @IsString()
    fileName: string;

    @ApiProperty({ description: 'File original name' })
    @IsNotEmpty()
    @IsString()
    originalName: string;
}
